# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

#osx_image: xcode7.3
#language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SpinnerBotRS.xcworkspace -scheme SpinnerBotRS-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
language: swift  #1
osx_image: xcode9.2 #2
xcode_workspace: Example/SpinnerBotRS.xcworkspace #3
xcode_scheme: SpinnerBotRS-Example #4
xcode_destination: platform=iOS Simulator,OS=11.2,name=iPhone X
